//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquerLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquerLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] COFlashFixer_DLL {
            get {
                object obj = ResourceManager.GetObject("COFlashFixer_DLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] COHook6022 {
            get {
                object obj = ResourceManager.GetObject("COHook6022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] COHook6176 {
            get {
                object obj = ResourceManager.GetObject("COHook6176", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] COHook6371 {
            get {
                object obj = ResourceManager.GetObject("COHook6371", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon ConquerLoaderLogo {
            get {
                object obj = ResourceManager.GetObject("ConquerLoaderLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;mysqldump xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///&lt;database name=&quot;serverdat&quot;&gt;
        ///	&lt;table_structure name=&quot;outenserver&quot;&gt;
        ///		&lt;field Field=&quot;id&quot; Type=&quot;int(10) unsigned&quot; Null=&quot;NO&quot; Key=&quot;PRI&quot; Default=&quot;&quot; Extra=&quot;&quot; /&gt;
        ///		&lt;field Field=&quot;ServerName&quot; Type=&quot;varchar(50)&quot; Null=&quot;NO&quot; Key=&quot;&quot; Default=&quot;0&quot; Extra=&quot;&quot; /&gt;
        ///		&lt;field Field=&quot;ServerIP&quot; Type=&quot;varchar(128)&quot; Null=&quot;NO&quot; Key=&quot;&quot; Default=&quot;0&quot; Extra=&quot;&quot; /&gt;
        ///		&lt;field Field=&quot;ServerPort&quot; Type=&quot;int(10) unsigned&quot; Null=&quot;NO&quot; Key=&quot;&quot; Default=&quot;0&quot; Extra=&quot;&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ServersXML {
            get {
                return ResourceManager.GetString("ServersXML", resourceCulture);
            }
        }
    }
}
