//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquerLoader {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquerLoader.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to List.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close CO.
        /// </summary>
        internal static string btnCloseCO {
            get {
                return ResourceManager.GetString("btnCloseCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detect.
        /// </summary>
        internal static string btnHelpGroupIcon {
            get {
                return ResourceManager.GetString("btnHelpGroupIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Modules.
        /// </summary>
        internal static string btnLogModules {
            get {
                return ResourceManager.GetString("btnLogModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plugins.
        /// </summary>
        internal static string btnPlugins {
            get {
                return ResourceManager.GetString("btnPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server.dat.
        /// </summary>
        internal static string btnServerDat {
            get {
                return ResourceManager.GetString("btnServerDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START.
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New +.
        /// </summary>
        internal static string btnWizard {
            get {
                return ResourceManager.GetString("btnWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close on finish.
        /// </summary>
        internal static string lblCloseOnFinish {
            get {
                return ResourceManager.GetString("lblCloseOnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLServer (Experimental).
        /// </summary>
        internal static string lblCLServer {
            get {
                return ResourceManager.GetString("lblCLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug Mode.
        /// </summary>
        internal static string lblDebugMode {
            get {
                return ResourceManager.GetString("lblDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable flash fix.
        /// </summary>
        internal static string lblDisableAutoFixFlash {
            get {
                return ResourceManager.GetString("lblDisableAutoFixFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fullscreen.
        /// </summary>
        internal static string lblFullscreen {
            get {
                return ResourceManager.GetString("lblFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icon of  Server in Login Server Screen.
        /// </summary>
        internal static string lblGroupIcon {
            get {
                return ResourceManager.GetString("lblGroupIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conquer executable name.
        /// </summary>
        internal static string lblHelpConquerExe {
            get {
                return ResourceManager.GetString("lblHelpConquerExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Port of your server.
        /// </summary>
        internal static string lblHelpGPort {
            get {
                return ResourceManager.GetString("lblHelpGPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group of this server in Login Screen.
        /// </summary>
        internal static string lblHelpGroup {
            get {
                return ResourceManager.GetString("lblHelpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address IP of your server.
        /// </summary>
        internal static string lblHelpIP {
            get {
                return ResourceManager.GetString("lblHelpIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login Port of your server.
        /// </summary>
        internal static string lblHelpLPort {
            get {
                return ResourceManager.GetString("lblHelpLPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of the server.
        /// </summary>
        internal static string lblHelpServerName {
            get {
                return ResourceManager.GetString("lblHelpServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version of Client (IMPORTANT).
        /// </summary>
        internal static string lblHelpVersion {
            get {
                return ResourceManager.GetString("lblHelpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HD Mode.
        /// </summary>
        internal static string lblHighResolution {
            get {
                return ResourceManager.GetString("lblHighResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servername change (V5717-).
        /// </summary>
        internal static string lblServerNameChange {
            get {
                return ResourceManager.GetString("lblServerNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title in Loader.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use of DirectX9 (Could have problems in some client).
        /// </summary>
        internal static string lblUseDX9 {
            get {
                return ResourceManager.GetString("lblUseDX9", resourceCulture);
            }
        }
    }
}
